# Generated by Django 3.2.7 on 2021-10-08 14:21

import api.models
import autoslug.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('color', colorfield.fields.ColorField(blank=True, default=None, max_length=18, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=api.models.get_name, slugify=api.models.transliterate_slugify)),
            ],
        ),
    ]
