# Generated by Django 3.2.7 on 2021-10-08 14:27

import api.models
import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=api.models.get_name, slugify=api.models.transliterate_slugify, unique=True),
        ),
    ]
